"""Generate proof-carrying variant sudoku fixtures.

Run from the project root::

    uv run python tools/generate_variant_fixtures.py

Each fixture is built, not borrowed, and ships with machine-checked
guarantees enforced right here before anything is written:

1. the puzzle has exactly one solution (CP-SAT enumeration proof);
2. the technique solver — an independent implementation — reaches the
   same solution without guessing;
3. the variant constraint is load-bearing: the same givens *without* the
   variant admit multiple solutions, so a regression that silently drops
   the variant constraint cannot pass the tests.

The generation itself is deterministic given the library version: the
base solution grid is CP-SAT's first enumerated solution for the empty
variant grid, and givens are stripped in fixed cell order.
"""

import json
import sys
from dataclasses import replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from puzzle_analyzer.sudoku import (
    SudokuPuzzle,
    analyze,
    count_solutions,
    solve_logically,
    to_line,
)
from puzzle_analyzer.sudoku.model import Cage, Variants

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures"


def first_solution(variants: Variants) -> tuple[int, ...]:
    empty = SudokuPuzzle(values=(0,) * 81, variants=variants)
    solutions = count_solutions(empty, limit=1)
    if not solutions:
        raise SystemExit(f"variant set is unsatisfiable: {variants}")
    return tuple(solutions[0])


def strip_givens(puzzle: SudokuPuzzle) -> SudokuPuzzle:
    """Remove givens (fixed order) while unique and guess-free-solvable."""
    current = puzzle
    for cell in range(81):
        if not current.values[cell]:
            continue
        grid = list(current.values)
        grid[cell] = 0
        trial = replace(current, values=tuple(grid))
        if len(count_solutions(trial, limit=2)) != 1:
            continue
        if not solve_logically(trial).solved:
            continue
        current = trial
    return current


def domino_cages(
    solution: tuple[int, ...], rows: range, columns: range
) -> tuple[Cage, ...]:
    """Horizontal two-cell cages tiling the given area, sums from the
    solution (consistent by construction)."""
    cages = []
    for r in rows:
        for c in columns[::2]:
            cells = (r * 9 + c, r * 9 + c + 1)
            cages.append(
                Cage(cells=cells, total=sum(solution[i] for i in cells))
            )
    return tuple(cages)


def spec_dict(puzzle: SudokuPuzzle) -> dict:
    variants = puzzle.variants
    spec: dict = {"givens": to_line(puzzle.values)}
    for flag in ("diagonal_down", "diagonal_up", "antiknight", "antiking"):
        if getattr(variants, flag):
            spec[flag] = True
    if variants.cages:
        spec["cages"] = [
            {
                "cells": [[i // 9, i % 9] for i in cage.cells],
                "sum": cage.total,
            }
            for cage in variants.cages
        ]
    if variants.extra_regions:
        spec["extra_regions"] = [
            [[i // 9, i % 9] for i in region]
            for region in variants.extra_regions
        ]
    return spec


def build(name: str, variants: Variants, *, cage_area: tuple | None = None) -> None:
    solution = first_solution(variants)
    if cage_area is not None:
        variants = replace(
            variants, cages=domino_cages(solution, *cage_area)
        )
    puzzle = strip_givens(SudokuPuzzle(values=solution, variants=variants))

    # Guarantee 1+2: unique, and the independent solver agrees, guess-free.
    analysis = analyze(puzzle)
    assert analysis.valid, f"{name}: not unique after stripping"
    assert analysis.solvable_without_guessing, f"{name}: needs guessing"
    assert analysis.solve.final_values == list(solution), f"{name}: mismatch"

    # Guarantee 3: the variant constraints are load-bearing.
    classic = SudokuPuzzle(values=puzzle.values)
    classic_count = len(count_solutions(classic, limit=2))
    assert classic_count >= 2, (
        f"{name}: classic rules alone already force this grid — the "
        f"variant fixture would not exercise the variant constraint"
    )

    fixture = {
        "provenance": (
            "generated by tools/generate_variant_fixtures.py: CP-SAT first "
            "solution for the empty variant grid, givens stripped in cell "
            "order while unique and technique-solvable"
        ),
        "spec": spec_dict(puzzle),
        "expected": to_line(solution),
        "classicSolutionCount": f"{classic_count}+",
        "grade": analysis.rating.grade,
        "givenCount": sum(1 for v in puzzle.values if v),
    }
    path = FIXTURES / f"{name}.json"
    path.write_text(json.dumps(fixture, indent=2) + "\n", encoding="utf-8")
    print(
        f"{name}: {fixture['givenCount']} givens, grade {analysis.rating.grade}, "
        f"classic-only solutions {fixture['classicSolutionCount']}"
    )


def main() -> None:
    build("sudoku_x", Variants(diagonal_down=True, diagonal_up=True))
    build("sudoku_antiknight", Variants(antiknight=True))
    build(
        "sudoku_killer",
        Variants(),
        cage_area=(range(0, 6), range(0, 8)),
    )
    build(
        "sudoku_killer_antiking",
        Variants(antiking=True),
        cage_area=(range(3, 9), range(1, 9)),
    )


if __name__ == "__main__":
    main()
