"""Tests for variant sudoku and the f-puzzles importer.

The fixtures are generated by ``tools/generate_variant_fixtures.py`` and
carry three machine-checked guarantees (uniqueness proof, independent
solver agreement, and variant-constraint necessity); the tests re-verify
all three from scratch so the guarantees hold in CI, not just at
generation time.
"""

import pytest

from puzzle_analyzer.core import hardening
from puzzle_analyzer.core.spec import SpecError
from puzzle_analyzer.sudoku import (
    SudokuPuzzle,
    analyze,
    count_solutions,
    fpuzzles,
    parse,
    to_line,
    validate,
)
from puzzle_analyzer.sudoku import grade as sudoku_grade
from puzzle_analyzer.sudoku import reductions as sudoku_reductions
from puzzle_analyzer.sudoku.model import king_pairs, knight_pairs

VARIANT_FIXTURES = [
    "sudoku_x",
    "sudoku_antiknight",
    "sudoku_killer",
    "sudoku_killer_antiking",
]


@pytest.mark.parametrize("name", VARIANT_FIXTURES)
class TestVariantFixtures:
    def test_unique_and_matches_expected(self, name, fixture):
        data = fixture(name)
        puzzle = parse(data["spec"])
        verdict = validate(puzzle)
        assert verdict.unique
        assert verdict.solution == data["expected"]

    def test_solvable_without_guessing_by_independent_solver(self, name, fixture):
        data = fixture(name)
        analysis = analyze(parse(data["spec"]))
        assert analysis.solvable_without_guessing
        assert to_line(analysis.solve.final_values) == data["expected"]

    def test_every_step_is_sound(self, name, fixture):
        """No technique may ever contradict the true solution."""
        data = fixture(name)
        analysis = analyze(parse(data["spec"]))
        solution = analysis.solution
        for step in analysis.solve.steps:
            for cell, digit in step.placements:
                assert solution[cell] == digit, step.description
            for cell, digit in step.eliminations:
                assert solution[cell] != digit, step.description

    def test_variant_constraint_is_load_bearing(self, name, fixture):
        """The same givens under classic rules must not be unique —
        proving the variant constraint actually participates."""
        data = fixture(name)
        puzzle = parse(data["spec"])
        classic = SudokuPuzzle(values=puzzle.values)
        assert len(count_solutions(classic, limit=2)) >= 2

    def test_hardening_engine_works_on_variants(self, name, fixture):
        data = fixture(name)
        puzzle = parse(data["spec"])
        report = hardening.suggest(
            puzzle,
            validate=validate,
            grade=sudoku_grade,
            reductions=sudoku_reductions,
        )
        assert report.viable
        for suggestion in report.suggestions[:2]:
            sub = validate(suggestion.puzzle)
            assert sub.unique
            assert sub.solution == data["expected"]


class TestVariantRules:
    def test_knight_pairs_are_each_counted_once(self):
        pairs = knight_pairs()
        assert len(pairs) == len({frozenset(p) for p in pairs})
        # Corner cell R1C1 (index 0) has exactly two knight moves.
        assert sum(1 for p in pairs if 0 in p) == 2

    def test_king_pairs_are_diagonal_only(self):
        for a, b in king_pairs():
            assert abs(a // 9 - b // 9) == 1 and abs(a % 9 - b % 9) == 1

    def test_conflicting_diagonal_givens_detected(self):
        grid = ["."] * 81
        grid[0], grid[80] = "5", "5"  # both on the R1C1-R9C9 diagonal
        spec = {"givens": "".join(grid), "diagonal_down": True}
        verdict = validate(parse(spec))
        assert not verdict.well_formed
        assert any("diagonal" in issue for issue in verdict.issues)
        # ...but perfectly legal in classic sudoku.
        assert validate(parse({"givens": "".join(grid)})).well_formed

    def test_conflicting_knight_givens_detected(self):
        grid = ["."] * 81
        grid[0], grid[2 * 9 + 1] = "7", "7"  # R1C1 and R3C2: knight's move
        verdict = validate(parse({"givens": "".join(grid), "antiknight": True}))
        assert not verdict.well_formed
        assert any("knight" in issue for issue in verdict.issues)

    def test_corrupted_cage_sum_kills_all_solutions(self, fixture):
        spec = fixture("sudoku_killer")["spec"]
        spec["cages"][0]["sum"] = 3 if spec["cages"][0]["sum"] != 3 else 4
        verdict = validate(parse(spec))
        assert verdict.well_formed
        assert verdict.solution_count == 0

    def test_infeasible_cage_is_malformed(self):
        spec = {
            "givens": "." * 81,
            "cages": [{"cells": [[0, 0], [0, 1]], "sum": 1}],
        }
        verdict = validate(parse(spec))
        assert not verdict.well_formed

    def test_duplicate_given_inside_cage_is_malformed(self):
        grid = ["."] * 81
        grid[0], grid[9] = "4", "4"  # same column: also a unit conflict
        spec = {
            "givens": "".join(grid),
            "cages": [{"cells": [[0, 0], [1, 0]], "sum": 8}],
        }
        verdict = validate(parse(spec))
        assert not verdict.well_formed
        assert any("cage" in issue for issue in verdict.issues)

    def test_list_givens_are_validated(self):
        # Codex review finding (PR #5): bad list-form givens used to
        # surface as IndexError deep in the solver.
        with pytest.raises(SpecError, match="81 cells"):
            parse({"givens": [5, 3, 0]})
        with pytest.raises(SpecError, match="digits 0-9"):
            parse({"givens": [12] + [0] * 80})
        with pytest.raises(SpecError, match="digits 0-9"):
            parse({"givens": ["x"] * 81})
        assert parse({"givens": [0] * 81}).values == (0,) * 81

    def test_x_geometry_has_29_units(self, fixture):
        puzzle = parse(fixture("sudoku_x")["spec"])
        assert len(puzzle.geometry.units) == 29
        names = puzzle.geometry.unit_names
        assert sum("diagonal" in name for name in names) == 2


class TestFPuzzles:
    def test_roundtrip_through_the_fpuzzles_format(self, fixture):
        spec = fixture("sudoku_x")["spec"]
        payload = fpuzzles.encode(spec)
        url = f"https://f-puzzles.com/?load={payload}"
        imported = parse(url)
        assert imported == parse(spec)

    def test_killer_cages_roundtrip(self, fixture):
        spec = fixture("sudoku_killer")["spec"]
        imported = parse({"fpuzzles": fpuzzles.encode(spec)})
        assert imported == parse(spec)
        assert validate(imported).unique

    def test_non_given_values_are_ignored(self):
        document = {
            "size": 9,
            "grid": [
                [
                    {"value": 5, "given": r == 0 and c == 0}
                    for c in range(9)
                ]
                for r in range(9)
            ],
        }
        spec = fpuzzles.convert(document)
        assert spec["givens"][0] == 5
        assert sum(1 for v in spec["givens"] if v) == 1

    def test_unsupported_features_fail_loudly(self):
        document = {
            "size": 9,
            "grid": [[{} for _ in range(9)] for _ in range(9)],
            "thermometer": [{"lines": [["R1C1", "R1C2"]]}],
        }
        with pytest.raises(SpecError, match=r"unsupported.*thermometer"):
            fpuzzles.convert(document)

    def test_cage_without_sum_fails_loudly(self):
        document = {
            "size": 9,
            "grid": [[{} for _ in range(9)] for _ in range(9)],
            "killercage": [{"cells": ["R1C1", "R1C2"]}],
        }
        with pytest.raises(SpecError, match="cage without a sum"):
            fpuzzles.convert(document)

    def test_garbage_payload_fails_loudly(self):
        with pytest.raises(SpecError, match="could not decode"):
            fpuzzles.decode("https://f-puzzles.com/?load=notbase64!!!")

    def test_diagonal_direction_mapping(self):
        # f-puzzles "diagonal-" is the R1C1->R9C9 diagonal.
        document = {
            "size": 9,
            "grid": [[{} for _ in range(9)] for _ in range(9)],
            "diagonal-": True,
        }
        spec = fpuzzles.convert(document)
        assert spec["diagonal_down"] and not spec["diagonal_up"]
